{% set name = "opentelemetry-instrumentation-fastapi" %}
{% set version = "0.37b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_fastapi-{{ version }}.tar.gz
  sha256: 84e50dc92b3ae65f4e18d0cad6538db267690361a55644553a5f3b32f64e2de9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation-asgi ==0.37b0
    - opentelemetry-instrumentation ==0.37b0
    - opentelemetry-semantic-conventions ==0.37b0
    - opentelemetry-util-http ==0.37b0
    # - requests ~=2.23
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-instrumentation-fastapi 
    # - httpx ~=0.22
    # - fastapi <=0.90.1

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-fastapi
  summary: OpenTelemetry FastAPI Instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
