{% set name = "opentelemetry-instrumentation-fastapi" %}
{% set version = "0.39b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_fastapi-{{ version }}.tar.gz
  sha256: 02d4d583a0a62efc9a94d489f1a736ca2905fb6f7d445ac686608de51d7e375b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation-asgi ==0.39b0
    - opentelemetry-instrumentation ==0.39b0
    - opentelemetry-semantic-conventions ==0.39b0
    - opentelemetry-util-http ==0.39b0
    # - requests ~=2.23
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-instrumentation-fastapi 
    # - httpx ~=0.22
    # - fastapi <=0.90.1
    # - requests ~=2.23
    # - opentelemetry-test-utils ==0.38b0
    # - opentelemetry-instrumentation-fastapi 
    # - httpx ~=0.22
    # - fastapi ~=0.58
    # - requests ~=2.23
    # - opentelemetry-test-utils ==0.39b0
    # - opentelemetry-instrumentation-fastapi 
    # - httpx ~=0.22
    # - fastapi ~=0.58

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-fastapi
  summary: OpenTelemetry FastAPI Instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
